#!/usr/bin/env bash
# Codex adapter — generates AGENTS.md in current directory
#
# Codex CLI reads AGENTS.md (https://agents.md/) at project root.
# This adapter compiles Coco skills + rules into a single AGENTS.md.
#
# Usage:
#   bash adapters/codex/install.sh             # write ./AGENTS.md
#   bash adapters/codex/install.sh -o PATH     # write to PATH
#   bash adapters/codex/install.sh --dry-run

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT="./AGENTS.md"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o) shift; OUTPUT=$1 ;;
    --dry-run) DRY_RUN=1 ;;
    --help|-h) grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

generate() {
  echo "# AGENTS.md"
  echo ""
  echo "Generated by Coco · adapters/codex/install.sh"
  echo "Source: $REPO_ROOT"
  echo ""
  echo "## Skills"
  echo ""
  for skill in "$REPO_ROOT/skills"/*/SKILL.md; do
    name=$(basename "$(dirname "$skill")")
    desc=$(awk -F': ' '/^description:/ {sub(/^description: */,""); gsub(/^"|"$/,""); print; exit}' "$skill")
    echo "- **$name** — $desc"
  done
  echo ""
  echo "## Commands"
  echo ""
  for ns in "$REPO_ROOT/commands"/*/; do
    nsname=$(basename "$ns")
    for cmd in "$ns"*.md; do
      [[ -f "$cmd" ]] || continue
      cname=$(basename "$cmd" .md)
      [[ "$cname" == "_index" ]] && continue
      echo "- /$nsname:$cname"
    done
  done
  echo ""
  echo "## Rules"
  echo ""
  for mdc in "$REPO_ROOT/rules/cursor-mdc"/*.mdc; do
    name=$(basename "$mdc" .mdc)
    echo "### $name"
    awk '/^---$/{f=!f; next} !f' "$mdc"
    echo ""
  done
}

if [[ $DRY_RUN -eq 1 ]]; then
  # Capture full output to temp file, then preview first 50 lines.
  # Avoids SIGPIPE under `set -o pipefail` when piping `generate | head`.
  TMP=$(mktemp)
  generate > "$TMP"
  head -50 "$TMP"
  echo "..."
  echo "(dry-run; full output would be written to $OUTPUT — $(wc -l < "$TMP") lines)"
  rm -f "$TMP"
else
  # Backup any existing AGENTS.md before overwrite (timestamped, never destroys).
  if [[ -f "$OUTPUT" ]]; then
    BACKUP="$OUTPUT.backup-$(date +%Y%m%d-%H%M%S)"
    cp "$OUTPUT" "$BACKUP"
    echo "Backed up existing $OUTPUT → $BACKUP"
  fi
  generate > "$OUTPUT"
  echo "Wrote $OUTPUT ($(wc -l < "$OUTPUT") lines)"
fi
