"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _home_dashboard from './home-dashboard.bones.json'

registerBones({
  "home-dashboard": _home_dashboard,
})
