#!/usr/bin/env bash
# GitHub Copilot CLI adapter — generates AGENTS.md and .github/copilot-instructions.md
#
# Usage:
#   bash adapters/github-copilot-cli/install.sh
#   bash adapters/github-copilot-cli/install.sh --systems gsd,brain
#   bash adapters/github-copilot-cli/install.sh --dry-run

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DRY_RUN=0
SYSTEMS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --systems) shift; IFS=',' read -ra SYSTEMS <<< "$1" ;;
    --help|-h) grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

run() { [[ $DRY_RUN -eq 1 ]] && echo "DRY: $*" || "$@"; }

echo "Coco · GitHub Copilot CLI adapter"
echo "Source: $REPO_ROOT"
echo "Target: $(pwd) (project root)"

# Generate AGENTS.md
AGENTS_CONTENT="# AGENTS.md — Generated by Coco for GitHub Copilot CLI
## Available Agents
"

for agent in "$REPO_ROOT/agents"/*.md; do
  [[ -f "$agent" ]] || continue
  name=$(basename "$agent" .md)
  [[ "$name" == "INDEX" || "$name" == "README" || "$name" == "PROMPT-DEFENSE" ]] && continue
  desc=$(grep -m1 "^description:" "$agent" 2>/dev/null | sed 's/^description: *"*//;s/"*$//' | head -c 120)
  AGENTS_CONTENT+="
### $name
$desc
"
done

for sys in "${SYSTEMS[@]}"; do
  sys_dir="$REPO_ROOT/systems/$sys"
  [[ -d "$sys_dir/agents" ]] || continue
  AGENTS_CONTENT+="
## System: $sys Agents
"
  for a in "$sys_dir/agents"/*.md; do
    [[ -f "$a" ]] || continue
    aname=$(basename "$a" .md)
    adesc=$(grep -m1 "^description:" "$a" 2>/dev/null | sed 's/^description: *"*//;s/"*$//' | head -c 120)
    AGENTS_CONTENT+="
### $aname
$adesc
"
  done
done

if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: write AGENTS.md ($(echo "$AGENTS_CONTENT" | wc -l) lines)"
else
  echo "$AGENTS_CONTENT" > AGENTS.md
  echo "Wrote: AGENTS.md"
fi

# Generate .github/copilot-instructions.md
INSTRUCTIONS="# Copilot Instructions — Generated by Coco

## Code Conventions
- Follow existing project patterns and naming conventions
- Use conventional commits for all commit messages
- Always run tests before committing changes
- Prefer explicit imports over wildcard imports

## Security
- Never hardcode secrets, API keys, or credentials
- Validate all user input before processing
- Use parameterized queries for database operations
- Sanitize output to prevent injection attacks

## Testing
- Write tests for new functionality
- Ensure existing tests pass before submitting changes
- Include edge cases and error handling in tests

## Documentation
- Update documentation when changing public APIs
- Add inline comments for complex logic
- Keep README and docs in sync with code changes
"

if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: write .github/copilot-instructions.md"
else
  mkdir -p .github
  echo "$INSTRUCTIONS" > .github/copilot-instructions.md
  echo "Wrote: .github/copilot-instructions.md"
fi

echo "Done."
