#!/usr/bin/env bash
# Aider CLI adapter — generates AGENTS.md and .aider.conf.yml in project root
#
# Usage:
#   bash adapters/aider/install.sh
#   bash adapters/aider/install.sh --systems gsd,brain
#   bash adapters/aider/install.sh --dry-run

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DRY_RUN=0
SYSTEMS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --systems) shift; IFS=',' read -ra SYSTEMS <<< "$1" ;;
    --help|-h) grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

run() { [[ $DRY_RUN -eq 1 ]] && echo "DRY: $*" || "$@"; }

echo "Coco · Aider CLI adapter"
echo "Source: $REPO_ROOT"
echo "Target: $(pwd) (project root)"

# Generate AGENTS.md
AGENTS_CONTENT="# AGENTS.md — Generated by Coco for Aider CLI
## Available Agents
"

for agent in "$REPO_ROOT/agents"/*.md; do
  [[ -f "$agent" ]] || continue
  name=$(basename "$agent" .md)
  [[ "$name" == "INDEX" || "$name" == "README" || "$name" == "PROMPT-DEFENSE" ]] && continue
  desc=$(grep -m1 "^description:" "$agent" 2>/dev/null | sed 's/^description: *"*//;s/"*$//' | head -c 120)
  AGENTS_CONTENT+="
### $name
$desc
"
done

# Add system agents if requested
for sys in "${SYSTEMS[@]}"; do
  sys_dir="$REPO_ROOT/systems/$sys"
  [[ -d "$sys_dir/agents" ]] || continue
  AGENTS_CONTENT+="
## System: $sys Agents
"
  for a in "$sys_dir/agents"/*.md; do
    [[ -f "$a" ]] || continue
    aname=$(basename "$a" .md)
    adesc=$(grep -m1 "^description:" "$a" 2>/dev/null | sed 's/^description: *"*//;s/"*$//' | head -c 120)
    AGENTS_CONTENT+="
### $aname
$adesc
"
  done
done

if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: write AGENTS.md ($(echo "$AGENTS_CONTENT" | wc -l) lines)"
else
  echo "$AGENTS_CONTENT" > AGENTS.md
  echo "Wrote: AGENTS.md"
fi

# Generate .aider.conf.yml
CONF_CONTENT="# .aider.conf.yml — Generated by Coco
# See https://aider.chat/docs/config.html for full reference

# Use conventional commits format
git_commit_format: '{type}: {subject}'

# Auto-commits enabled
auto_commits: true

# Read-only files (Coco artifacts — don't modify)
read_only_files:
  - AGENTS.md
  - .aider.conf.yml
"

# Add skill references as read-only context
CONF_CONTENT+="
# Coco skills available as context (reference only):
# Skills are in $REPO_ROOT/skills/
# Invoke via /skill-name or ask the agent to use them
"

if [[ $DRY_RUN -eq 1 ]]; then
  echo "DRY: write .aider.conf.yml"
else
  echo "$CONF_CONTENT" > .aider.conf.yml
  echo "Wrote: .aider.conf.yml"
fi

echo "Done."
