#!/usr/bin/env python3
"""
build_commands.py — Super Intelligence Team slash-command generator.

Single source of truth for the SI command surface. Stamps out
~/.claude/commands/SI-<TEAM>-<Verb>.md files from a shared header + per-verb
bodies, with all pre-mortem mitigations baked in:

  #1 on-command refresh    -> SI-<TEAM>-Refresh maintenance verb
  #2 output tiers          -> shared header: short default + --deep
  #3 voice-check           -> SI-<TEAM>-VoiceCheck maintenance verb
  #4 template-gen          -> THIS SCRIPT (one source, regenerate any time)
  #5 confidence-tiered     -> shared header Step 0: auto-proceed on high
     fast-approve             confidence, gate only when ambiguous
  #6 stance validator      -> shared header: post-output validation pass
                              + SI-<TEAM>-Verify maintenance verb

CoCo-as-orchestrator: action verbs route selection THROUGH CoCo for
context-aware persona picking, falling back to the standalone orchestrator
when CoCo is disabled.

Usage:
    python3 build_commands.py                 # generate all known teams
    python3 build_commands.py --team AI       # generate one team
    python3 build_commands.py --list          # list what would be generated
    python3 build_commands.py --shims         # also (re)write back-compat shims

Re-run any time the header, a verb body, or a team config changes.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

COMMANDS_DIR = Path(os.environ.get("COCO_SI_COMMANDS_DIR", Path.home() / ".claude" / "commands"))
# Bundle-relative: this file lives at <root>/systems/superintelligence/ai/scripts/build_commands.py,
# so parents[3] == <root>/systems, and data_dir "superintelligence/<team>" resolves under it.
# Override with COCO_SI_REPO if the data lives elsewhere.
REPO = Path(os.environ.get("COCO_SI_REPO", Path(__file__).resolve().parents[3]))

# ─────────────────────────────────────────────────────────────────────────────
# TEAM REGISTRY — add a team here, re-run, get 25 commands. That is the whole
# multi-team story.
# ─────────────────────────────────────────────────────────────────────────────
TEAMS = {
    "AI": {
        "team_id": "ai-super-intelligence",
        "team_name": "AI Super Intelligence Team",
        "data_dir": "superintelligence/ai",            # under REPO
        "persona_count": 59,
        "cell_count": 8,
        "gap_doc": "EXPANSION.md",                     # roster-gap doc for :Recruit
        "built": True,
        "legacy_prefix": None,                         # shims deleted 2026-05-28
    },
    "Eng": {
        "team_id": "engineering-super-intelligence",
        "team_name": "Engineering Super Intelligence Team",
        "data_dir": "superintelligence/engineering",
        "persona_count": 70,
        "cell_count": 11,
        "gap_doc": "ROSTER.md",
        "built": True,
        "legacy_prefix": None,
    },
    "PD": {
        "team_id": "product-design-super-intelligence",
        "team_name": "Product & Design Super Intelligence Team",
        "data_dir": "superintelligence/product-design",
        "persona_count": 56,
        "cell_count": 8,
        "gap_doc": "ROSTER.md",
        "built": True,
        "legacy_prefix": None,
    },
    # Future teams (uncomment + populate data_dir when scaffolded):
    # "Finance": {"team_id": "finance-super-intelligence", "team_name": "Finance Super Intelligence Team", "data_dir": "superintelligence/finance", "persona_count": 0, "cell_count": 0, "built": False, "legacy_prefix": None},
    # "Compliance": {"team_id": "compliance-super-intelligence", "team_name": "Compliance Super Intelligence Team", "data_dir": "superintelligence/compliance", "persona_count": 0, "cell_count": 0, "built": False, "legacy_prefix": None},
    # "Finance": {"team_id": "finance-super-intelligence", "team_name": "Finance Super Intelligence Team", "data_dir": "superintelligence/finance", "persona_count": 0, "cell_count": 0, "built": False, "legacy_prefix": None},
    # "Compliance": {"team_id": "compliance-super-intelligence", "team_name": "Compliance Super Intelligence Team", "data_dir": "superintelligence/compliance", "persona_count": 0, "cell_count": 0, "built": False, "legacy_prefix": None},
}

# ─────────────────────────────────────────────────────────────────────────────
# SHARED HEADER — injected into every ACTION verb. Carries CoCo orchestration,
# output tiers, fast-approve, and the stance validator. Placeholders:
#   {TEAM_SHORT} {TEAM_ID} {TEAM_NAME} {DATA_DIR} {VERB_TITLE} {VERB_DESC}
# ─────────────────────────────────────────────────────────────────────────────
ACTION_HEADER = """# /SI-{TEAM_SHORT}-{VERB_TITLE} — {VERB_DESC}

> Action verb of the {TEAM_NAME}. Orchestrated through CoCo. Generated by `build_commands.py` — do not hand-edit; edit the generator and regenerate.

## Team data layer

- Registry: `{REPO}/{DATA_DIR}/registry.json`
- Personas: `{REPO}/{DATA_DIR}/personas/<slug>.md`
- Cells: `{REPO}/{DATA_DIR}/cells/<cell-slug>.md`
- Convene template (shared): `{REPO}/superintelligence/templates/convene.md`

## Flags (all action verbs)

- `--deep` — full output (mitigation #2). Default output is the SHORT tier.
- `--no-orchestrate` — skip selection; use all {TEAM_ID} personas.
- `--cells <comma-list>` — manual cell scope; skip orchestration.
- `--personas <comma-list>` — manual slug scope; skip orchestration.
- `--coco-off` — force the standalone orchestrator instead of CoCo.

## Step 0 — Orchestration via CoCo (mitigation #3 wiring + #5 fast-approve)

Unless `--no-orchestrate` / `--cells` / `--personas` is supplied:

1. **Route selection through CoCo.** Invoke CoCo (the `coco` skill) with the prompt plus the recent conversation context, asking it to pick 16-32 `{TEAM_ID}` personas. CoCo reads `{REPO}/{DATA_DIR}/registry.json` and scores by domain-match (40%) + cell-coverage (30%) + productive-conflict pairing (30%). CoCo's conversation context is what makes the pick better than a cold standalone score.
   - **Fallback:** if `~/.coco/disabled` exists OR `--coco-off` is set, invoke `/SI-{TEAM_SHORT}-Orchestrate "<prompt>"` (the light standalone scorer) instead.

2. **Confidence-tiered fast-approve (mitigation #5).** Do NOT block by default.
   - **HIGH confidence** (clear domain match, team spans 5-8 cells cleanly): print a 1-line team summary and AUTO-PROCEED.
     > `N picked. Heavy <cells>, light <cells>. Conflict pairs: X/Y, P/Q. Proceeding — reply 'edit' to redline.`
   - **LOW confidence** (weak domain match, lopsided cell coverage, or prompt is high-stakes/irreversible): use `AskUserQuestion` with approve / edit / re-pick / reject.
   - Hard 16-32 band: a redline outside the band asks for confirmation.

3. Capture the approved slug list. If the user rejects, STOP.

## Step 1 — Read approved persona files

For each approved slug, read `{REPO}/{DATA_DIR}/personas/<slug>.md`. Internalize `signature_moves`, `mental_models`, `voice_style`, `public_stances`, `recent_signal_12mo`, `blind_spots`.

"""

# Per-verb unique pipeline + output schema (the part that differs by verb).
# The shared FOOTER (output tiers + validator + conventions) is appended after.
ACTION_VERBS = {
    "analyse": {
        "title": "Analyse",
        "desc": "multi-persona analysis of a topic",
        "body": """## Step 2 — Per-persona analysis

Each approved persona gives a 3-5 sentence read of the topic in their voice, anchored to a `public_stance` (cite the `evidence_url`).

## Step 3 — Synthesis

Rank the strongest cross-cell signals. Each signal names a lead voice AND a counter-voice (if none, flag `no counter surfaced`).
""",
    },
    "decide": {
        "title": "Decide",
        "desc": "decision matrix with named attribution",
        "body": """## Step 2 — Identify options

Parse explicit options from the prompt (`A or B`). If none, list 2-4 plausible options and confirm via `AskUserQuestion` before building the matrix.

## Step 3 — Per-persona verdict

Each persona picks across the options in 1-2 sentences, anchored to a `public_stance` (cite `evidence_url`).

## Step 4 — Decision output

- SHORT tier: aggregate vote tally + recommended option + 3 named dissents.
- `--deep`: full persona × option matrix grouped by cell.

Recommendation MUST be a clear pick — no "it depends." Name the deciding factor and the load-bearing dissent.
""",
    },
    "review": {
        "title": "Review",
        "desc": "multi-persona critique of a doc, PR, or design",
        "body": """## Step 2 — Load target

File path → read it. PR URL → `gh pr view` + `gh pr diff`. Quoted text → use directly.

## Step 3 — Per-persona findings

Each persona classifies findings CRITICAL / MAJOR / MINOR / SUGGESTION. Every finding: quoted location + reason (their voice) + suggested fix.

## Step 4 — Output

- SHORT: deduplicated findings table by severity + SHIP / FIX-THEN-SHIP / DO-NOT-SHIP verdict.
- `--deep`: full per-persona review.
""",
    },
    "re-analyse": {
        "title": "Re-Analyse",
        "desc": "rerun an earlier analysis with new evidence",
        "body": """## Step 2 — Load prior + evidence

`--prior <path>` reads a prior analysis. `--evidence "<text>"` supplies what changed. Need at least one.

## Step 3 — Per-persona update

Each persona marks position change YES / NO / PARTIAL, anchored to a `recent_signal_12mo` (prefer entries postdating the prior analysis).

## Step 4 — Output

Diff table: each signal marked REVERSED / STRENGTHENED / WEAKENED / UNCHANGED / NEW.
""",
    },
    "pre-mortem": {
        "title": "Pre-Mortem",
        "desc": "what kills this in 12 months",
        "body": """## Step 2 — Frame the failure

State the prompt as: "It is 12 months from now. <plan> shipped and failed. What killed it?"

## Step 3 — Per-persona failure mode

Each persona names one failure mode (mine their `blind_spots`), an early-warning sign (observable), and a likelihood (LOW/MED/HIGH).

## Step 4 — Output

Ranked failure-mode table + cluster patterns + concrete mitigations. Name the single biggest threat AND the most-overlooked threat.
""",
    },
    "post-mortem": {
        "title": "Post-Mortem",
        "desc": "root-cause analysis of a failure",
        "body": """## Step 2 — Establish the gap

State expected vs actual vs gap. Prompt for any missing piece.

## Step 3 — Per-persona 5 Whys

Each persona digs a 5-level why-chain to a proposed root cause, anchored to a `signature_move` or `public_stance`.

## Step 4 — Output

Convergent vs divergent root-cause claims. Pick the single most-likely root cause with counter-evidence. Immediate / short-term / structural remediation.
""",
    },
    "full-cycle": {
        "title": "Full-Cycle",
        "desc": "compound 5-step chained flow (heaviest verb)",
        "body": """## Compound flow — chains real subcommand invocations

Warn the user this is ~5x latency, confirm, then chain:

1. `/SI-{TEAM_SHORT}-Review "<topic>"` → capture findings.
2. `/SI-{TEAM_SHORT}-Analyse` on the surfaced findings → capture signals.
3. Inline mitigate-risk: each persona proposes mitigations for top risks.
4. `/SI-{TEAM_SHORT}-Decide` with findings + mitigations baked in → decision.
5. Finalize: a single action plan citing the chain of evidence with named owners.

Each chained step runs its own CoCo orchestration. `--deep` propagates to every step.
""",
    },
    "tradeoff": {
        "title": "Tradeoff",
        "desc": "structured A-vs-B comparison",
        "body": """## Step 2 — Parse options + dimensions

Split on `vs` (cap 4 options). Pick 4-7 comparison dimensions; confirm with user if non-obvious.

## Step 3 — Per-persona scoring

Score each option on each dimension STRONG / OK / WEAK / N/A, anchored to a `public_stance`.

## Step 4 — Output

Dimensions × options table with the dominant voice per cell. Name the recommended option AND the most-opposed cell. Surface counter-intuitive scores.
""",
    },
    "plan": {
        "title": "Plan",
        "desc": "phased plan synthesis with attribution",
        "body": """## Step 2 — Decompose into phases

3-6 phases, each with deliverable, duration, owner cell + lead persona, dependencies.

## Step 3 — Per-phase synthesis

Approach in the owner cell's voice + 1-3 named dissents per phase + one risk (named persona).

## Step 4 — Output

Phase table: phase / duration / owner cell / lead voice / deliverable. Critical path + highest-risk phase named.
""",
    },
    "design": {
        "title": "Design",
        "desc": "architecture design pass with per-decision attribution",
        "body": """## Step 2 — Decompose into components

4-8 components, each with responsibility, owner cell, interfaces.

## Step 3 — Per-component decisions

Each key decision: chosen option / driven-by persona (+ evidence_url) / tradeoff accepted / alternative + who'd prefer it. One named failure mode per component.

## Step 4 — Output

Component map + cross-cutting concerns table (latency/cost/safety/observability/extensibility) + mandatory soundness check by a theory voice and a safety voice + build sequence.
""",
    },
    "vote": {
        "title": "Vote",
        "desc": "yes/no per persona on a binary question",
        "body": """## Step 2 — Confirm binary

If not binary, redirect to Decide or Tradeoff and STOP.

## Step 3 — Per-persona vote

Each persona votes YES / NO / ABSTAIN with a one-sentence rationale + `evidence_url`. ABSTAIN is rare — push back before allowing it.

## Step 4 — Output

Tally overall + by cell. Tie-breaker analysis if within 2 votes. Strongest YES arg + strongest NO arg. Clear recommendation.
""",
    },
    "debug": {
        "title": "Debug",
        "desc": "multi-lens diagnosis of a problem",
        "body": """## Step 2 — Per-persona hypothesis

Each persona proposes a root-cause hypothesis grounded in their own `signature_moves` + `mental_models` (derive the lens live from each persona's registry record — do NOT assume a fixed domain) + the first diagnostic test they'd run.

## Step 3 — Output

Ranked hypotheses (cross-cell support × falsifiability × domain match) + recommended test ORDER (cheapest-first). Name what each test eliminates.
""",
    },
    "stress-test": {
        "title": "Stress-Test",
        "desc": "adversarial review, no diplomacy",
        "body": """## Step 2 — Frame adversarially

"Attack this proposal. Find every reason it fails." Flip each persona's `blind_spots` into an attack angle.

## Step 3 — Per-persona attacks

1-3 sharp attacks per persona, each with a 6-month failure prediction + `evidence_url`. Stay in voice; no hedging.

## Step 4 — Output

Severity matrix (SHIP-BLOCKING / MAJOR / MINOR × REFUTABLE / LOAD-BEARING / UNCERTAIN). Single most-damaging attack. Verdict: SHIP / HARDEN-THEN-SHIP / REFRAME / DO-NOT-SHIP.
""",
    },
    "defend": {
        "title": "Defend",
        "desc": "steelman a position from a chosen persona or cell",
        "body": """## Step 2 — Pick defender

`as <slug>` or `as <cell>` → skip orchestration, defend solo/cell. No `as` → orchestrate, bias HARD toward personas whose stances align with the position.

## Step 3 — Build the steelman

Sharpen the claim in the defender's framing. 3-6 load-bearing claims, each cited. Defuse the 3-5 strongest counter-objections. Mandatory "what would change my mind" section. Voice-fidelity check before emitting.
""",
    },
    "roast": {
        "title": "Roast",
        "desc": "blunt one-line critique per persona, no diplomacy",
        "body": """## Step 2 — Orchestrate toward sharp voices

Bias selection toward the bluntest, most direct public voices in THIS team's roster — derive them live from each persona's `voice_style` in the registry (pick the ones whose style reads as direct / unfiltered / contrarian).

## Step 3 — Per-persona roast

ONE line per persona, ≤30 words, in their voice, naming a specific weakness. Order most-cutting first.

## Step 4 — Output

The single line that hurt most + the convergent critique (if ≥N personas land the same weakness) + exactly ONE constructive line: what would silence the roasts.
""",
    },
}

# Shared footer for ACTION verbs — output tiers + stance validator + conventions.
ACTION_FOOTER = """## Output tiers (mitigation #2)

- **DEFAULT = SHORT.** Verdict / ranked table / synthesis + top-3 named dissents + one "what this missed" line. ~10-20 lines. Dissent is ALWAYS visible even in short mode (Barnes constraint).
- **`--deep`** expands to the full per-persona detail.

## Stance validation (mitigation #6)

After producing output, run a validation pass:

1. Every quoted stance MUST trace to that persona's `public_stances`, `v2_panel_attribution`, or `recent_signal_12mo`. Unmatched → label `[extrapolated]` inline.
2. Every cited stance shows its `evidence_url`. No URL → downgrade to `[extrapolated]`.
3. If >25% of the output's claims are `[extrapolated]`, prepend a warning: "Low grounding — many claims are inferred, not documented."

## Conventions

1. Attribution every line — name a persona or a cell, never "the team said."
2. Full English prose in output. No caveman compression.
3. Registry is source of truth; re-read each invocation.
4. Confidence-tiered approval, never pure auto.
5. Dissent always visible, even in short tier.

ARGUMENTS: {{ARGUMENTS}}
"""

# IDENTITY verbs — skip orchestration entirely (explicit override path).
IDENTITY_VERBS = {
    "ask": {
        "title": "Ask",
        "desc": "1-on-1 with one persona in their voice",
        "body": """Expects `<persona-slug> "<question>"`. No orchestration.

Read `{REPO}/{DATA_DIR}/personas/<slug>.md`. Answer as that persona — voice_style register, signature_moves, mental_models. Cite `public_stances` inline with `evidence_url`. Acknowledge a `blind_spot` if the question hits one. Close with `— <Real Name>, <affiliation>, <cell>`.

Stance validation (mitigation #6): every claim traces to the persona file or is labeled `[extrapolated]`.
""",
    },
    "huddle": {
        "title": "Huddle",
        "desc": "whole-cell synthesis on a topic",
        "body": """Expects `<cell-slug> "<topic>"`. No orchestration — the user picked the cell.

Read `{REPO}/{DATA_DIR}/cells/<cell-slug>.md` + every persona file in the cell. Per-persona stance (lead-drivers first) → cell consensus (mark UNANIMOUS/SPLIT) → cell dissent → cross-cell tensions to expect.
""",
    },
    "meeting": {
        "title": "Meeting",
        "desc": "full-panel convene with attribution",
        "body": """Expects `"<prompt>"`. No orchestration — brings the whole team.

Read `{REPO}/superintelligence/templates/convene.md` and follow its structure: inputs → per-cell stances → cross-cell disagreement → synthesis verdict → anchor quotes. For per-cell stances, read the 2-4 most relevant persona files per cell; scan the rest from registry metadata. `--deep` reads all.
""",
    },
    "read": {
        "title": "Read",
        "desc": "print a persona file inline",
        "body": """Expects `<persona-slug>`. Validate against registry, read `{REPO}/{DATA_DIR}/personas/<slug>.md`, print verbatim (no voice channeling). Append a quick-actions footer (Ask / Huddle / research dir path).
""",
    },
}

ROSTER_VERBS = {
    "recruit": {
        "title": "Recruit",
        "desc": "propose new persona candidates for a domain gap",
        "body": """Expects `<domain> "<why>"`. Read `{REPO}/{DATA_DIR}/registry.json` (and `{REPO}/{DATA_DIR}/{GAP_DOC}` if it exists) to see the current roster and known gaps. Validate the gap is real (not already covered, not already queued). Propose 2-3 named candidates with affiliation + cited URL + suggested cell + productive-conflict pairing. Does NOT write personas — recommends the parallel research-agent build. Offer to record the candidates in `{GAP_DOC}`.
""",
    },
}

# MAINTENANCE verbs — realize mitigations #1, #3, #6.
MAINTENANCE_VERBS = {
    "refresh": {
        "title": "Refresh",
        "desc": "owner-triggered recency update (mitigation #1)",
        "body": """Expects `<slug>` | `--stale` (last_verified > 90d) | `--all`.

For each target persona: read the file, web-search latest, update `affiliations_2026` + `recent_signal_12mo` + `last_verified`. Preserve everything else. Re-run `build_registry.py` after. Report what changed per persona (old → new).

Fires ONLY when the user invokes it. No cron, no auto-trigger.
""",
    },
    "voicecheck": {
        "title": "VoiceCheck",
        "desc": "voice-fidelity test (mitigation #3, cheapest version)",
        "body": """Cheapest-version voice fidelity test — no heavy harness.

1. **Golden transcripts:** pick 6 anchor personas live from this team's registry (highest `confidence` + most distinct `voice_style`); generate a sample answer to a fixed prompt, compare against each one's `voice_style` + `signature_moves`. Flag drift.
2. **Blind-attribution:** strip names from 5 persona outputs; a fresh read guesses who. Can't tell apart → voices collapsing → flag the pair.

Report a fidelity score per checked persona and a list of collapsed/drifting voices. Run after persona-file edits or on demand.
""",
    },
    "verify": {
        "title": "Verify",
        "desc": "re-check a prior output's citations (mitigation #6)",
        "body": """Expects the last output (or `--output <path>`). For every attributed stance in the output, check it traces to the named persona's `public_stances` / `v2_panel_attribution` / `recent_signal_12mo`. Emit a table: claim / persona / FOUND (evidence_url) | EXTRAPOLATED | CONTRADICTED. Summary grounding score.
""",
    },
}


def dispatcher_body(short: str, cfg: dict) -> str:
    return f"""# /SI-{short} — {cfg['team_name']} dispatcher

> No-arg: print roster + cell heatmap. Generated by `build_commands.py`.

## Step 1 — Read registry

Read `{REPO}/{cfg['data_dir']}/registry.json`. If missing, tell the user to run `build_registry.py` and STOP.

## Step 2 — Roster mode (no args)

Print an ANSI-style roster: team name, {cfg['persona_count']} personas, {cfg['cell_count']} cells, per-cell counts + example personas (derive live from registry), and the command surface below.

## Command surface

- `/SI-{short}-Orchestrate "<prompt>"` — pick 16-32 personas (via CoCo) + approval gate
- Identity: `/SI-{short}-Ask <slug> "<q>"` · `/SI-{short}-Huddle <cell> "<topic>"` · `/SI-{short}-Meeting "<prompt>"` · `/SI-{short}-Read <slug>`
- Roster: `/SI-{short}-Recruit <domain> "<why>"`
- Action: Analyse · Decide · Review · Re-Analyse · Pre-Mortem · Post-Mortem · Full-Cycle · Tradeoff · Plan · Design · Vote · Debug · Stress-Test · Defend · Roast
- Maintenance: `/SI-{short}-Refresh` · `/SI-{short}-VoiceCheck` · `/SI-{short}-Verify`

All action verbs: `--deep` (full output), `--no-orchestrate`, `--cells`, `--personas`, `--coco-off`.

## Step 3 — Free text with no verb

If the user passes a free-text prompt and no verb, route through CoCo to pick the right verb, then run it.

ARGUMENTS: {{{{ARGUMENTS}}}}
"""


def orchestrate_body(short: str, cfg: dict) -> str:
    return f"""# /SI-{short}-Orchestrate — pick 16-32 personas (standalone fallback)

> Light standalone selector. CoCo is the primary orchestrator; this runs when CoCo is disabled or `--coco-off`. Generated by `build_commands.py`.

## Step 1 — Read registry (metadata only)

Read `{REPO}/{cfg['data_dir']}/registry.json`. Do NOT read persona files. Do NOT load CoCo.

## Step 2 — Score every persona

`total = 0.40*domain_match + 0.30*cell_coverage + 0.30*conflict_pairing`. Greedy pick with re-scoring after each pick. Seed top-5 by domain, then broaden cells, then reinforce conflict pairs.

## Step 3 — Confidence-tiered approval (mitigation #5)

HIGH confidence → 1-line summary + auto-proceed. LOW → AskUserQuestion (approve/edit/re-pick/reject). Hard 16-32 band; out-of-band redline asks confirmation.

## Step 4 — Return approved roster

Emit `APPROVED_ROSTER:` followed by one slug per line for the calling verb to consume.

ARGUMENTS: {{{{ARGUMENTS}}}}
"""


def render_action(short: str, cfg: dict, verb_key: str, verb: dict) -> str:
    head = ACTION_HEADER.format(
        TEAM_SHORT=short, TEAM_ID=cfg["team_id"], TEAM_NAME=cfg["team_name"],
        DATA_DIR=cfg["data_dir"], REPO=REPO, VERB_TITLE=verb["title"], VERB_DESC=verb["desc"],
    )
    body = verb["body"].format(TEAM_SHORT=short, DATA_DIR=cfg["data_dir"], REPO=REPO,
                               GAP_DOC=cfg.get("gap_doc", "ROSTER.md"))
    return head + body + "\n" + ACTION_FOOTER


def render_simple(short: str, cfg: dict, verb: dict, kind: str) -> str:
    body = verb["body"].format(TEAM_SHORT=short, DATA_DIR=cfg["data_dir"], REPO=REPO,
                               GAP_DOC=cfg.get("gap_doc", "ROSTER.md"))
    return (
        f"# /SI-{short}-{verb['title']} — {verb['desc']}\n\n"
        f"> {kind} verb of the {cfg['team_name']}. Generated by `build_commands.py`.\n\n"
        f"{body}\n\nARGUMENTS: {{{{ARGUMENTS}}}}\n"
    )


def files_for_team(short: str, cfg: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    out[f"SI-{short}.md"] = dispatcher_body(short, cfg)
    out[f"SI-{short}-Orchestrate.md"] = orchestrate_body(short, cfg)
    for k, v in ACTION_VERBS.items():
        out[f"SI-{short}-{v['title']}.md"] = render_action(short, cfg, k, v)
    for v in IDENTITY_VERBS.values():
        out[f"SI-{short}-{v['title']}.md"] = render_simple(short, cfg, v, "Identity")
    for v in ROSTER_VERBS.values():
        out[f"SI-{short}-{v['title']}.md"] = render_simple(short, cfg, v, "Roster")
    for v in MAINTENANCE_VERBS.values():
        out[f"SI-{short}-{v['title']}.md"] = render_simple(short, cfg, v, "Maintenance")
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--team", help="generate one team (e.g. AI)")
    ap.add_argument("--list", action="store_true", help="list files without writing")
    args = ap.parse_args()

    teams = {args.team: TEAMS[args.team]} if args.team else TEAMS
    if args.team and args.team not in TEAMS:
        sys.exit(f"Unknown team {args.team!r}. Known: {list(TEAMS)}")

    total = 0
    for short, cfg in teams.items():
        files = files_for_team(short, cfg)
        for name, content in files.items():
            path = COMMANDS_DIR / name
            if args.list:
                print(f"  would write {path}")
            else:
                path.write_text(content, encoding="utf-8")
            total += 1
        if not args.list:
            print(f"Team {short}: wrote {len(files)} commands to {COMMANDS_DIR}")
    print(f"{'Would generate' if args.list else 'Generated'} {total} command files.")


if __name__ == "__main__":
    main()
